mode: deployment

image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s

command:
  name: otelcol-k8s

config:
  receivers:
    otlp:
      protocols:
        grpc: {}
        http: {}

  processors:
    batch: {}

  exporters:
    debug: {}

  service:
    pipelines:
      metrics:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]

      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]

      logs:
        receivers: [otlp]
        processors: [batch]
        exporters: [debug]