receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  prometheusremotewrite:
    endpoint: http://victoriametrics-victoria-metrics-single-server.observability.svc.cluster.local:8428/api/v1/write

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheusremotewrite]