apiVersion: apps/v1
kind: Deployment

metadata:
  name: catalog-api
  namespace: opensre

spec:
  replicas: 1

  selector:
    matchLabels:
      app: catalog-api

  template:
    metadata:
      labels:
        app: catalog-api

    spec:
      containers:
        - name: catalog-api

          image: localhost/catalog-api:v1

          imagePullPolicy: Never

          ports:
            - containerPort: 8000